const problems=[
{id:1,group:'기본',title:'직접 대입',kind:'스피드',q:`<span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→1</span></span><span class="sqrtx"><span class="rad">x+3</span></span></span>`,type:'mc',choices:['1','2','3','4'],ans:'2',base:10,hints:['x가 1에 가까워질 때 x+3은 어떤 값에 가까워지는지 먼저 생각해 보세요.','x+3이 4에 가까워지면 √(x+3)은 어떤 값에 가까워질까요?'],explain:'√(1+3)=√4=2'},
{id:2,group:'기본',title:'절댓값과 발산',kind:'예측',q:`<span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→2</span></span><span class="fr"><span class="top">1</span><span class="bot">|x−2|</span></span></span>`,type:'mc',choices:['0','1','+∞','존재하지 않음'],ans:'+∞',base:10,hints:['|x−2|는 항상 0 이상입니다.','x→2이면 분모는 0의 양의 방향으로 가까워집니다.'],explain:'분모 |x−2|→0⁺이므로 +∞로 발산합니다.'},
{id:3,group:'기본',title:'최고차항 보기',kind:'스피드',q:`<span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→∞</span></span><span>(−x<span class="sup">2</span>+x)</span></span>`,type:'mc',choices:['−∞','−1','0','+∞'],ans:'−∞',base:10,hints:['x가 아주 클 때 x²과 x 중 어느 항이 더 큰 영향을 주는지 보세요.'],explain:'최고차항 −x²가 지배하므로 −∞입니다.'},
{id:4,group:'기본',title:'무한대에서의 분수',kind:'스피드',q:`<span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→−∞</span></span><span>(1+<span class="fr"><span class="top">2</span><span class="bot">x</span></span>)</span></span>`,type:'mc',choices:['−∞','−1','0','1'],ans:'1',base:10,hints:['x→−∞이면 2/x는 어디로 가나요?'],explain:'2/x→0이므로 1+2/x→1입니다.'},
{id:5,group:'기본',title:'차수 비교',kind:'스피드',q:`<span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→−∞</span></span><span class="fr"><span class="top">x<span class="sup">3</span>−2x</span><span class="bot">x<span class="sup">2</span>+1</span></span></span>`,type:'mc',choices:['−∞','−1','0','+∞'],ans:'−∞',base:11,hints:['분자와 분모를 x²으로 나누면 판단하기 쉬워집니다.'],explain:'(x−2/x)/(1+1/x²)에서 분자는 −∞, 분모는 1로 갑니다.'},
{id:6,group:'기본',title:'최고차항 계수',kind:'스피드',q:`<span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→∞</span></span><span class="fr"><span class="top">(2x+1)(x−1)</span><span class="bot">6x<span class="sup">2</span>+5</span></span></span>`,type:'mc',choices:['1/6','1/3','1/2','2/3'],ans:'1/3',base:11,hints:['분자를 전개하면 최고차항은 2x²입니다.'],explain:'최고차항의 계수 비 2/6=1/3입니다.'},
{id:7,group:'기본',title:'오답 탐정',kind:'함정',q:`<span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→2⁻</span></span><span class="fr"><span class="top">x<span class="sup">2</span>−2x</span><span class="bot">|x−2|</span></span></span>`,type:'trapAnswer',base:13,steps:['① x²−2x = x(x−2)로 인수분해한다.','② x→2⁻이므로 |x−2| = x−2 로 둔다.','③ 따라서 식은 x가 되어 극한값은 2이다.'],ansIndex:1,answerChoices:['−2','0','2','존재하지 않음'],finalAns:'−2',hints:['2⁻는 x가 2보다 작은 쪽에서 다가온다는 뜻입니다.','x<2이면 x−2는 음수입니다.'],explain:'잘못된 부분은 ②입니다. x<2이므로 |x−2|=−(x−2), 따라서 극한값은 −2입니다.'},
{id:8,group:'기본',title:'유리화 카드',kind:'조작',q:`<span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→5</span></span><span class="fr"><span class="top"><span class="sqrtx"><span class="rad">x+4</span></span>−3</span><span class="bot">x−5</span></span></span>`,type:'mc',choices:['1/3','1/6','1/9','6'],ans:'1/6',base:12,hints:['분자에 근호가 있는 차의 형태이므로 켤레식을 이용해 유리화해 보세요.','분자와 분모에 √(x+4)+3을 곱하면 식이 간단해집니다.'],explain:'√(x+4)+3을 곱해 유리화하면 1/(√(x+4)+3)이 되고, x→5일 때 극한값은 1/6입니다.'},
{id:9,group:'기본',title:'파라미터 암호',kind:'입력',q:`<div class="multilineEq"><span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→−1</span></span><span class="fr"><span class="top">x<span class="sup">2</span>+ax+b</span><span class="bot">x+1</span></span><span>=2</span></span><div style="font-size:18px">일 때, <i>ab</i>의 값</div></div>`,type:'input',ans:['12'],base:14,hints:['극한값이 유한하려면 x=−1에서 분자도 0이어야 합니다.','분자가 (x+1)로 나누어떨어져야 합니다.'],explain:'a=4, b=3이므로 ab=12입니다.'},
{id:10,group:'도전',title:'조건으로 함수 찾기',kind:'도전',boss:true,q:`<div class="multilineEq"><span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→∞</span></span><span class="fr"><span class="top">f(x)</span><span class="bot">2x+3</span></span><span>=2,</span><span style="margin-left:.5em"></span><span class="limbox"><span class="lim">lim</span><span class="sub">x→1</span></span><span>f(x)=3</span></span><div style="font-size:18px">다항함수 <i>f(x)</i>에 대하여 <i>f(2)</i>의 값</div></div>`,type:'input',ans:['7'],base:16,hints:['첫 번째 극한이 0이 아닌 유한값이므로 f(x)는 일차식입니다.','최고차항의 계수는 4입니다.'],explain:'f(x)=4x−1이므로 f(2)=7입니다.'},
{id:11,group:'도전',title:'좌극한 = 우극한',kind:'도전',boss:true,q:`<div class="multilineEq"><span class="eq"><span>f(x)=</span><span class="casebox"><span class="casebrace">{</span><span class="cases"><span>ax+5</span><span>(x&lt;a)</span><span>4x+1</span><span>(x≥a)</span></span></span></span><span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→a</span></span><span>f(x)=b</span></span><div style="font-size:18px">일 때, <i>a+b</i>의 값</div></div>`,type:'input',ans:['11'],base:16,hints:['x→a에서 극한이 존재하려면 좌극한과 우극한이 같아야 합니다.','a²+5 = 4a+1을 풀어보세요.'],explain:'(a−2)²=0이므로 a=2, b=9, 따라서 a+b=11입니다.'},
{id:12,group:'도전',title:'근과 극한 조건',kind:'도전',boss:true,q:`<div class="multilineEq"><span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→1</span></span><span class="fr"><span class="top">f(x)</span><span class="bot">x−1</span></span><span>×</span><span class="limbox"><span class="lim">lim</span><span class="sub">x→−1</span></span><span class="fr"><span class="top">f(x)</span><span class="bot">x+1</span></span><span>=−12</span></span><span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→∞</span></span><span>{ f(<span class="fr"><span class="top">1</span><span class="bot">x</span></span>)−2 }=0</span></span><div style="font-size:18px">최고차항의 계수가 1인 삼차함수 <i>f(x)</i>에 대하여 <i>f(3)</i></div></div>`,type:'input',ans:['8'],base:18,hints:['첫 번째 조건의 두 극한이 유한하려면 f(1)=0, f(−1)=0이어야 합니다.','f(x)=(x−1)(x+1)(x−a)로 두세요.','두 번째 조건에서 x→∞이면 1/x→0입니다.'],explain:'조건 (가)에서 a=±2, 조건 (나)에서 f(0)=2이므로 a=2. 따라서 f(3)=8입니다.'},
{id:13,group:'도전',title:'그래프 방향 읽기',kind:'그래프',boss:true,q:`<span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→−1⁺</span></span><span>f(x+1)</span><span>+</span><span class="limbox"><span class="lim">lim</span><span class="sub">x→1⁺</span></span><span>f(−x)</span></span>`,type:'input',ans:['3'],base:17,graph:true,hints:['첫째 항에서 u=x+1이라 두면 u→0⁺입니다.','둘째 항에서 u=−x라 두면 u→−1⁻입니다.'],explain:'그래프에서 lim(u→0⁺)f(u)=2, lim(u→−1⁻)f(u)=1이므로 합은 3입니다.'},
{id:14,group:'도전',title:'부등식으로 함수 찾기',kind:'도전',boss:true,q:`<div class="multilineEq"><span class="eq"><span>3x<span class="sup">2</span>−5x ≤ f(x)−2x<span class="sup">3</span> ≤ 3x<span class="sup">2</span>+5</span><span style="font-size:.72em">(x&gt;0)</span></span><span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→1</span></span><span class="fr"><span class="top">f(x)−5</span><span class="bot">x−1</span></span><span>=7</span></span><div style="font-size:18px">다항함수 <i>f(x)</i>에 대하여 <i>f(2)</i></div></div>`,type:'input',ans:['23'],base:20,hints:['g(x)=f(x)−2x³−3x²로 두어 보세요.','부등식에서 g(x)는 일차 이하의 다항함수여야 합니다.','두 번째 극한이 유한하므로 먼저 f(1)=5를 얻고, f(x)−5를 (x−1)로 묶어 보세요.'],explain:'g(x)=ax+b로 두고 f(1)=5에서 a+b=0을 얻습니다. f(x)−5를 (x−1)로 묶어 극한값 7을 적용하면 a=−5, b=5이므로 f(2)=23입니다.'},
{id:15,group:'도전',title:'치환으로 무한대 연결',kind:'도전',boss:true,q:`<div class="multilineEq"><span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→0⁺</span></span><span class="fr"><span class="top">x f(<span class="fr"><span class="top">1</span><span class="bot">x</span></span>)−1</span><span class="bot">1−x</span></span><span>=2</span></span><div style="font-size:18px">다항함수 <i>f(x)</i>에 대하여</div><span class="eq"><span class="limbox"><span class="lim">lim</span><span class="sub">x→∞</span></span><span class="fr"><span class="top">f(x)</span><span class="bot">x</span></span></span></div>`,type:'input',ans:['3'],base:19,hints:['t=1/x로 치환하세요.','x→0⁺이면 t→∞입니다.','식은 (f(t)−t)/(t−1) 형태로 바뀝니다.'],explain:'f(t)=at+b로 보면 a−1=2이므로 a=3, 따라서 lim f(x)/x=3입니다.'}
];
let state={name:'',info:'',xp:0,hints:0,miss:0,cleared:{},unknown:{},firstTry:{},usedHints:{},current:null};
let stageTimer=null,stageStartMs=null,lastShownSecond=-1;
function stopStageTimer(){if(stageTimer){clearInterval(stageTimer);stageTimer=null}}
function startStageTimer(p){stopStageTimer();const a=document.getElementById('timerArea');if(!a)return;if(p.id>9||state.cleared[p.id]){a.innerHTML='';stageStartMs=null;return}stageStartMs=Date.now();lastShownSecond=-1;const draw=()=>{const elapsed=Math.floor((Date.now()-stageStartMs)/1000)+1;if(elapsed===lastShownSecond)return;lastShownSecond=elapsed;const over=elapsed>30;const warn=elapsed>=21&&!over;const pct=Math.min(100,elapsed/30*100);a.innerHTML=`<div class="timerWrap ${over?'over':(warn?'warn':'')}"><div class="timerTop"><span class="timerLabel">${over?'시간 초과 · −0.1점':'⏱ 경과 시간'}</span><span class="timerClock timerTick">${elapsed}초</span></div><div class="timerBar"><div class="timerFill" style="width:${pct}%"></div></div></div>`};draw();stageTimer=setInterval(draw,200)}
function basicTimePenalty(p){return p.id<=9&&stageStartMs&&(Date.now()-stageStartMs)>30000?0.1:0}
function showHow(){document.getElementById('how').classList.toggle('hidden')}
function startGame(){state.name=(document.getElementById('teamName').value||'무명 팀').trim();state.info='';document.getElementById('setup').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('playerLabel').textContent=state.name;renderMap();updateStats()}
function resetGame(){stopStageTimer();if(!confirm('진행 기록을 모두 지우고 처음부터 시작할까요?'))return;state={name:state.name,info:'',xp:0,hints:0,miss:0,cleared:{},unknown:{},firstTry:{},usedHints:{},current:null};document.getElementById('resultPanel').classList.add('hidden');document.getElementById('gamePanel').classList.add('hidden');document.getElementById('mapPanel').classList.remove('hidden');renderMap();updateStats()}
function unlocked(id){if(id<=9)return true;return Object.keys(state.cleared).filter(k=>+k<=9).length>=6}
function renderMap(){const g=document.getElementById('stageGrid');g.innerHTML='';problems.forEach(p=>{const b=document.createElement('button');b.className='stage';if(!unlocked(p.id))b.classList.add('locked');if(state.cleared[p.id])b.classList.add('cleared');b.disabled=!unlocked(p.id);const stars=p.base>=19?'★★★':p.base>=16?'★★':'★';b.innerHTML=`<div class="num">${p.group} ${p.group==='기본'?p.id:p.id-9}</div><div class="name">${p.title}</div><div class="meta"><span class="star">${stars}</span> · ${p.base} XP</div><span class="badge ${p.boss?'boss':''} ${p.kind==='함정'?'trap':''}">${state.unknown[p.id]?'모름':(state.cleared[p.id]?'CLEAR':p.kind)}</span>`;b.onclick=()=>openStage(p.id);g.appendChild(b)})}
function updateStats(){document.getElementById('xp').textContent=state.xp;document.getElementById('clearCount').textContent=Object.keys(state.cleared).length+'/15';document.getElementById('hintCount').textContent=state.hints;document.getElementById('missCount').textContent=state.miss}
function graphSvg(){return `<div class="graphWrap"><img src="${GRAPH_DATA}" alt="원본 형성평가의 함수 y=f(x) 그래프" style="max-width:420px;width:100%;height:auto;display:block;margin:0 auto"></div>`}
function openStage(id){const p=problems.find(x=>x.id===id);state.current=id;document.getElementById('mapPanel').classList.add('hidden');document.getElementById('resultPanel').classList.add('hidden');document.getElementById('gamePanel').classList.remove('hidden');document.getElementById('stageKind').textContent=`${p.group} · ${p.kind}`;document.getElementById('stageTitle').textContent=`${p.group} ${p.group==='기본'?p.id:p.id-9}. ${p.title}`;document.getElementById('questionArea').innerHTML=`<div class="question">${p.q}</div>${p.graph?graphSvg():''}<p class="instructions">풀이 과정은 활동지에 적은 뒤, 아래에서 답을 확인하세요.</p>`;renderInteraction(p);document.getElementById('messageArea').innerHTML='';renderToolbar(p);startStageTimer(p)}
function choiceDisplay(pid,index,c){return c}
function renderInteraction(p){const box=document.getElementById('interactionArea');if(p.type==='mc'){box.innerHTML=`<div class="choices">${p.choices.map((c,i)=>`<button class="choice" onclick="checkMC(${p.id},${i},this)">${choiceDisplay(p.id,i,c)}</button>`).join('')}</div>`}else if(p.type==='input'){box.innerHTML=`<div class="answerRow"><input id="answerInput" inputmode="decimal" placeholder="정답 입력"><button class="primary" onclick="checkInput(${p.id})">확인</button></div>`;setTimeout(()=>{const el=document.getElementById('answerInput');if(el)el.addEventListener('keydown',e=>{if(e.key==='Enter')checkInput(p.id)})},0)}else if(p.type==='trapAnswer'){box.innerHTML=`<p class="instructions"><b>1단계.</b> 잘못된 풀이를 선택하세요.</p><div class="trapList">${p.steps.map((s,i)=>`<button class="trapStep" onclick="checkTrapFirst(${p.id},${i},this)">${s}</button>`).join('')}</div><div id="stage7answer"></div>`}}
function renderToolbar(p){const u=state.usedHints[p.id]||0;document.getElementById('toolbar').innerHTML=`${u<p.hints.length&&!state.cleared[p.id]?`<button class="ghost" onclick="useHint(${p.id})">힌트 보기 (-2 XP)</button>`:''}${p.id>=10&&!state.cleared[p.id]?`<button class="danger" onclick="markUnknown(${p.id})">모름</button>`:''}${state.cleared[p.id]&&!state.unknown[p.id]?`<button class="ghost" onclick="showExplanation(${p.id})">풀이 핵심 보기</button>`:''}`}
function markUnknown(id){const p=problems.find(x=>x.id===id);if(p.id<10||state.cleared[id])return;if(!confirm('이 도전 문제를 「모름」으로 표시할까요? 점수는 얻지 못하지만 결과 화면에는 기록됩니다.'))return;stopStageTimer();state.unknown[id]=true;state.cleared[id]=true;updateStats();message('「모름」으로 기록했습니다. 이 문제는 0점으로 처리되고 최종 결과에서 확인할 수 있습니다.','info');renderToolbar(p);renderMap();if(Object.keys(state.cleared).length===15)setTimeout(showResult,700)}
function useHint(id){const p=problems.find(x=>x.id===id),u=state.usedHints[id]||0;if(u>=p.hints.length)return;state.usedHints[id]=u+1;state.hints++;state.xp-=2;message(`<b>힌트 ${u+1}</b> · ${p.hints[u]}`,'info');updateStats();renderToolbar(p)}
function normalize(s){return String(s).trim().replace(/\s+/g,'').replace(/−/g,'-').replace(/∞/g,'inf').toLowerCase()}
function checkMC(id,index,btn){const p=problems.find(x=>x.id===id);if(state.cleared[id])return;if(normalize(p.choices[index])===normalize(p.ans)){btn.classList.add('correct');clearStage(p)}else{btn.classList.add('wrong');wrongTry(p,'다시 생각해 보세요.')}}
function checkTrapFirst(id,index,btn){const p=problems.find(x=>x.id===id);if(state.cleared[id])return;if(index===p.ansIndex){document.querySelectorAll('.trapStep').forEach(b=>b.disabled=true);btn.classList.add('correct');document.getElementById('stage7answer').innerHTML=`<p class="instructions" style="margin-top:20px"><b>2단계.</b> 그렇다면 실제 극한값은 얼마일까요?</p><div class="choices">${p.answerChoices.map((c,i)=>`<button class="choice" onclick="checkTrapFinal(${p.id},${i},this)">${c}</button>`).join('')}</div>`;message('오류를 정확히 찾았습니다. 이제 실제 극한값까지 선택하세요.','info')}else{btn.classList.add('wrong');wrongTry(p,'이 줄은 오류가 아닙니다. 다시 찾아보세요.')}}
function checkTrapFinal(id,index,btn){const p=problems.find(x=>x.id===id);if(state.cleared[id])return;if(normalize(p.answerChoices[index])===normalize(p.finalAns)){btn.classList.add('correct');clearStage(p)}else{btn.classList.add('wrong');wrongTry(p,'극한값이 아닙니다. 절댓값을 없앤 뒤 식을 다시 확인해 보세요.')}}
function checkInput(id){const p=problems.find(x=>x.id===id);if(state.cleared[id])return;const v=document.getElementById('answerInput').value;if(p.ans.some(a=>normalize(a)===normalize(v)))clearStage(p);else wrongTry(p,'정답이 아닙니다. 풀이를 다시 확인해 보세요.')}
function wrongTry(p,text){state.miss++;state.firstTry[p.id]=false;state.xp-=3;updateStats();message(`−3 XP · ${text}`,'bad')}
function clearStage(p){const penalty=basicTimePenalty(p);stopStageTimer();state.cleared[p.id]=true;state.xp+=p.base-penalty;updateStats();const tm=p.id<=9?(penalty?' · 30초 초과 −0.1 XP':' · 30초 안에 해결'):'';message(`STAGE CLEAR! +${p.base}${tm}<br><span style="font-weight:600">${p.explain}</span>`,'good');renderToolbar(p);renderMap();if(Object.keys(state.cleared).length===15)setTimeout(showResult,700)}
function showExplanation(id){const p=problems.find(x=>x.id===id);message(`<b>풀이 핵심</b> · ${p.explain}`,'info')}
function message(t,y){document.getElementById('messageArea').innerHTML=`<div class="msg ${y}">${t}</div>`}
function backToMap(){stopStageTimer();state.current=null;document.getElementById('gamePanel').classList.add('hidden');document.getElementById('mapPanel').classList.remove('hidden');renderMap()}
function showResult(){stopStageTimer();document.getElementById('gamePanel').classList.add('hidden');document.getElementById('mapPanel').classList.add('hidden');document.getElementById('resultPanel').classList.remove('hidden');const xp=state.xp,g=xp>=190?'S':xp>=170?'A':xp>=150?'B':'C';document.getElementById('grade').textContent=g;document.getElementById('resultText').textContent=`${state.name}의 LIMIT QUEST가 완료되었습니다.`;document.getElementById('finalXp').textContent=xp;document.getElementById('finalHints').textContent=state.hints+'회';document.getElementById('finalMiss').textContent=state.miss+'회';const resultItems=problems.map(p=>{const label=`${p.group} ${p.group==='기본'?p.id:p.id-9}`;const hadWrong=state.firstTry[p.id]===false;const isUnknown=!!state.unknown[p.id];return `<div class="problemResultItem ${isUnknown?'unknown':(hadWrong?'retry':'ok')}">${label} · ${isUnknown?'모름':(hadWrong?'틀린 적 있음':'한 번에 정답')}</div>`}).join('');document.getElementById('problemResultList').innerHTML=`<div class="problemResultGrid">${resultItems}</div>`}
function downloadResult(){const rows=problems.map(p=>`${p.group} ${p.group==='기본'?p.id:p.id-9}. ${p.title}: ${state.unknown[p.id]?'모름':(state.firstTry[p.id]===false?'틀린 적 있음':'한 번에 정답')}`).join('\n');const text=`LIMIT QUEST 결과\n이름/팀: ${state.name}\n최종 XP: ${state.xp}\n힌트 사용: ${state.hints}회\n오답 횟수: ${state.miss}회\n클리어: ${Object.keys(state.cleared).length}/15\n\n${rows}`;const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`LIMIT_QUEST_${state.name.replace(/[\\/:*?"<>|]/g,'_')}_결과.txt`;a.click();URL.revokeObjectURL(a.href)}